# Generated by fusen: do not edit by hand

#' check_data_integrity
#'
#' @param dataset a dataset
#'
#' @return
#' A message
#' @export
#'
#' @examples
#' 
#' 

#' # Example dataset
#' 
#' datafile <- system.file("nyc_squirrels_sample.csv", package = "integrity")
#' nyc_squirrels <- read.csv(datafile)
#' 
#' head(nyc_squirrels)
#'   
#' check_data_integrity(dataset = nyc_squirrels)
check_data_integrity <- function(dataset) {
  
  ifelse(("+" %in%  dataset$primary_fur_color), print("STOP"), print("The data integrity is OK"))
}
